[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gcrostore"
description = "Crostore web app integrated with Google system"
readme = "README.md"
requires-python = "~=3.10"
license = "MIT"
authors = [
  { name = "Shuhei Nitta", email = "huisintheta@gmail.com" }
]
keywords = []
classifiers = []
dependencies = [
  "crostore @ git+https://github.com/huisint/crostore@master",
  "google-api-python-client~=2.62.0",
  "fastapi~=0.85.0",
  "pydantic[email]~=1.10.2",
  "jinja2~=3.1.2",
  "markdown~=3.4.1",
]
dynamic = ["version"]

[project.urls]
Documentation = ""
Homepage = "https://github.com/huisint/gcrostore"

[project.optional-dependencies]
test = [
  "pytest~=7.1.3",
  "pytest-cov~=4.0.0",
  "pytest-describe~=2.0.1",
  "mypy~=0.982",
  "flake8~=5.0.4",
  "isort~=5.10.1",
  "black~=22.8.0",
  "google-api-python-client-stubs~=1.11.0",
  "types-Markdown~=3.4.2",
]
dev = [
  "pre-commit~=2.20.0",
  "uvicorn~=0.18.3",
  "google-auth-oauthlib",
]
doc = []
prod = [
  "uvicorn[standard]~=0.18.3",
  "bugsnag~=4.2.1",
]

[tool.hatch.version]
path = "src/gcrostore/__init__.py"

[tool.hatch.metadata]
allow-direct-references = true

[tool.mypy]
python_version = "3.10"
strict = true

[[tool.mypy.overrides]]
module = [
  "google.*",
  "google_auth_oauthlib.*",
]
ignore_missing_imports = true

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "--cov=gcrostore"
testpaths = ["tests"]
