---
services:
  main:
    image: mcr.microsoft.com/vscode/devcontainers/python:3.11
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
      SMTP_HOST: postfix
      SMTP_PORT: 25
      SMTP_FROM: Crostore
      CLIENT_ID: $GOOGLE_CLIENT_ID
      CLIENT_SECRET: $GOOGLE_CLIENT_SECRET
    volumes:
      - ..:/workspaces:cache
    command: sleep infinity
  selenium:
    image: selenium/standalone-chrome:111.0
    shm_size: 2g
  postfix:
    image: juanluisbaptiste/postfix:1.7
    environment:
      SERVER_HOSTNAME: crostore.com
      SMTP_PORT: 587
      SMTP_SERVER: $SMTP_SERVER
      SMTP_USERNAME: $SMTP_USERNAME
      SMTP_PASSWORD: $SMTP_PASSWORD
